### ISSUE TITLE
 Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8

### ISSUE THREAD

**Issue by yiyi17** [antvis/gatsby-theme-antv#368]
Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8

安装失败，M1电脑

info sharp Downloading https://npmmirror.com/mirrors/sharp-libvips/v8.10.5/libvips-8.10.5-darwin-arm64v8.tar.br
ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
  CC(target) Release/obj.target/nothing/../_node-addon-api@3.2.1@node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:24:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xx/.nvm/versions/node/v14.18.0/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/xx/.nvm/versions/node/v14.18.0/bin/node" "/Users/xx/.nvm/versions/node/v14.18.0/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xx/code/felab/mysite/node_modules/_sharp@0.27.2@sharp
gyp ERR! node -v v14.18.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok

**Comment by stillmatic** [comment]
run `brew install vips` to install vips binaries, then the commands worked for me
